.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "INTERVALS" "1" "June 2011" "" ""
.
.SH "NAME"
\fBintervals\fR \-\- manage your timesheets
.
.SH "SYNOPSIS"
\fBintervals\fR [add\-time] [\-\-date 2011\-03\-14 \.\.\.] [\-\-project name] [\-\-hours 4] [\-\-billable] [\-\-description "Hello World"]
.
.P
\fBintervals\fR list\-projects
.
.P
\fBintervals\fR ls [\-\-date 2011\-03\-14\.\.2011\-03\-17]
.
.P
\fBintervals\fR list\-timers
.
.P
\fBintervals\fR start\-timer
.
.P
\fBintervals\fR get\-timer id
.
.P
\fBintervals\fR delete\-timer id
.
.P
\fBintervals\fR completion
.
.P
\fBintervals\fR [version|\-\-version]
.
.P
\fBintervals\fR [help|\-\-help]
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-\-date\fR:
  Specify the date\. You can add multiple date\.
  You can also specify a range of date (2011\-06\-17\.\.2011\-06\-14) or a string (yesterday, today) \.
  When you are using a range, date value must be in ISO 8601 format (YYYY\-MM\-DD) and should be in the account\'s local time\.
  Default date is today\.
.
.IP "\(bu" 4
\fB\-\-project\fR:
  Name of a previously saved project\. Use \fBintervals\fR list\-projects to list projects saved\.
.
.IP "\(bu" 4
\fB\-\-hours\fR:
  Number of hours\. Default 8 hours\.
.
.IP "\(bu" 4
\fB\-\-billable\fR:
  Is your hours billable ? Default non billable\.
.
.IP "\(bu" 4
\fB\-\-description\fR:
  Time entry description\. Default is empty\.
.
.IP "\(bu" 4
\fB\-v\fR, \fB\-\-version\fR:
  Show intervals version and exit\.
.
.IP "\(bu" 4
\fB\-\-help\fR
  Show this help page\.
.
.IP "" 0
.
.SH "REQUEST LIMITS"
Requests are not to exceed:
.
.IP "\(bu" 4
100 requests per minute per IP
.
.IP "\(bu" 4
6000 requests per day per customer account
.
.IP "" 0
.
.SH "EXAMPLES"
.
.nf
$ intervals \-\-date 2011\-04\-07
$ intervals \-\-date 2011\-04\-07 \-\-date 2011\-04\-08
$ intervals \-\-date 2011\-04\-07 \-\-billable
$ intervals \-\-date 2011\-04\-07\.\.2011\-04\-15
$ intervals \-\-date yesterday
$ intervals \-\-hours 4
.
.fi
.
.SH "Completion"
Intervals include a basic completion script for bash\.
.
.IP "" 4
.
.nf
intervals completion >> ~/\.bashrc
.
.fi
.
.IP "" 0
.
.SH "ENVIRONMENT VARIABLES"
.
.IP "\(bu" 4
\fBXDG_CONFIG_HOME\fR
.
.IP "\(bu" 4
\fBPAGER\fR
.
.IP "" 0
.
.SH "BUGS"
Please report bugs in GitHub \fIhttps://github\.com/francois2metz/node\-intervals/issues\fR
.
.SH "COPYRIGHT"
Copyright 2011 François de Metz
